services:
  client-react-vite:
    image: client-react-vite
    build:
      context: /mnt/c/Users/Ss/devops-project/01-example-web-application/client-react-vite
      dockerfile: /mnt/c/Users/Ss/devops-project/02-building-container-images/client-react-vite/Dockerfile.3
    init: true
    ports:
      - "5173:5173"
    networks:
      - my-network
    volumes:
      - type: bind
        source: /mnt/c/Users/Ss/devops-project/01-example-web-application/client-react-vite/
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
      - type: volume
        target: /mnt/c/Users/Ss/devops-project/03-container-registries/vite.config.js
    restart: unless-stopped

  api-golang:
    image: api-golang
    build:
      context: /mnt/c/Users/Ss/devops-project/01-example-web-application/api-golang
      dockerfile: /mnt/c/Users/Ss/devops-project/02-building-container-images/api-golang/Dockerfile.8
      target: dev
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    ports:
      - "8080:8080"
    networks:
      - my-network
    volumes:
      - type: bind
        source: /mnt/c/Users/Ss/devops-project/01-example-web-application/api-golang
        target: /app
    restart: unless-stopped

  api-node:
    image: api-node
    build:
      context: /mnt/c/Users/Ss/devops-project/01-example-web-application/api-node
      dockerfile: /mnt/c/Users/Ss/devops-project/02-building-container-images/api-node/Dockerfile.9
      target: dev
    init: true
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    depends_on:
      - db
    ports:
      - "3030:3030"
    networks:
      - my-network
    volumes:
      - type: bind
        source: /mnt/c/Users/Ss/devops-project/01-example-web-application/api-node
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
    restart: unless-stopped
  
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata:
networks:
  my-network:

    