services:
  postgres_db:
     image: postgres:15.6-alpine
     environment: 
       - POSTGRES_PASSWORD=admin
     ports: 
       - 5432:5432
     networks:
       - my_network
     volumes:
       - pg_data:/var/lib/postgresql/data
     restart: unless-stopped

  api-node_web:
     image: api-node
     build: 
       context: /mnt/c/Users/Ss/devops-project/01-example-web-application/api-node
       dockerfile: /mnt/c/Users/Ss/devops-project/02-building-container-images/api-node/Dockerfile.9
     init: true
     ports:
       - 8080:8080
     networks:
       - my_network
     environment: 
       -  DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
     depends_on:
       - postgres_db
     restart: unless-stopped
volumes:
   pg_data:
networks:
   my_network:
