name: image-ci

on:
 push:
   branches: 
     - master
   tags:
     - "v*"
jobs:
  build-tag-push:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
      
    - name: Docker Metadata 
      id: meta
      uses: docker/metadata-action@v6.0.0
      with: 
        images: |
          rudreshayd/getting-started
        tags: |
          type=raw,value=latest
          type=ref,event=branch
          type=ref, event=pr
          tyoe=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value={{date 'YYYYMMDD'}}.{{sha}}
          
    
    
    
 
